name: ci

on:
  push:
    branches: [ ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5 #3.0.2
      with:
        name: menedev/stingy-caddy
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        default_branch: main
        tag_semver: true
